title: HG.fi
description: TypeScript modules for building standalone, production-grade full stack apps
url: "https://hg.fi"
exclude:
  - vendor
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
lang: en
include: [".well-known"]
